interface Membership {user_id:string;artist_id:string|null;venue_id:string|null;administrator:number}
// Readable labels for the account list: artist and venue names, and each account's email where a request recorded it.
const names={artists:new Map<string,string>(),venues:new Map<string,string>(),people:new Map<string,string>()};
const make=(tag:string,text='')=>{const node=document.createElement(tag);node.textContent=text;return node};
export async function initAccountAssignments(){
 const form=document.querySelector<HTMLFormElement>('[data-account-form]'),status=document.querySelector<HTMLElement>('[data-account-status]'),list=document.querySelector<HTMLElement>('[data-account-list]');
 if(!form||!status||!list)return;
 const user=form.elements.namedItem('userId') as HTMLInputElement,artist=form.elements.namedItem('artistId') as HTMLSelectElement,venue=form.elements.namedItem('venueId') as HTMLSelectElement,administrator=form.elements.namedItem('administrator') as HTMLInputElement,save=form.querySelector<HTMLButtonElement>('button')!;
 async function api(path:string,body?:unknown){const response=await fetch('/api/community/'+path,{method:body?'PUT':'GET',headers:body?{'Content-Type':'application/json','x-aaj-prototype':'local'}:{},body:body?JSON.stringify(body):undefined});const result=await response.json();if(!response.ok)throw new Error(result.error||'Unable to load account access.');return result}
 async function refresh(){const {memberships}=await api('memberships');list!.replaceChildren();for(const member of memberships as Membership[]){const button=document.createElement('button');button.type='button';button.textContent='';const who=make('strong',names.people.get(member.user_id)||`Account ending ${member.user_id.slice(-6)}`);if(member.user_id===form!.dataset.currentUser)who.append(' (you)');button.append(who,make('span',[member.artist_id?`Artist: ${names.artists.get(member.artist_id)||member.artist_id}`:'No artist page',member.venue_id?`Venue: ${names.venues.get(member.venue_id)||member.venue_id}`:'No venue',...(member.administrator?['Administrator']:[])].join(' · ')));button.addEventListener('click',()=>{user.value=member.user_id;artist.value=member.artist_id||'';venue.value=member.venue_id||'';administrator.checked=member.administrator===1;status!.textContent='Review these permissions, then save to apply changes.';user.focus()});const row=document.createElement('p');row.append(button);list!.append(row)}}
 try{const {records}=await api('state');for(const record of records){const data=record.payload;if(data){if(record.collection==='artists'&&data.name)names.artists.set(record.id,data.name);if(record.collection==='applications'){if(data.name&&!names.artists.has(record.id))names.artists.set(record.id,data.name);if(data.submittedBy&&data.email)names.people.set(data.submittedBy,String(data.email).toLowerCase())}if(record.collection==='venues'){if(data.name)names.venues.set(record.id,data.name);if(data.submittedBy&&data.email&&!names.people.has(data.submittedBy))names.people.set(data.submittedBy,String(data.email).toLowerCase())}}if(record.collection==='applications'&&record.payload?.status==='approved'&&record.payload.invitationAccepted)artist.add(new Option(record.payload.name||record.id,record.id));if(record.collection==='venues'&&record.payload?.status==='approved')venue.add(new Option(record.payload.name||record.id,record.id))}await refresh();save.disabled=false}catch(error){status.textContent=error instanceof Error?error.message:'Unable to load account access.'}
 const requestedUser=new URLSearchParams(location.search).get('user');if(requestedUser){user.value=requestedUser;status.textContent='The applicant account is ready. Choose its approved workspace, then save.'}
 form.addEventListener('submit',async event=>{event.preventDefault();save.disabled=true;status.textContent='Checking the Clerk account and saving permissions…';try{await api('memberships',{userId:user.value.trim(),artistId:artist.value||null,venueId:venue.value||null,administrator:administrator.checked});await refresh();status.textContent='Account access saved. The person can reload their account page to see the assignment.'}catch(error){status.textContent=error instanceof Error?error.message:'Unable to save account access.'}finally{save.disabled=false}});
}
