interface Membership {user_id:string;artist_id:string|null;venue_id:string|null;administrator:number}
export async function initAccountAssignments(){
 const form=document.querySelector<HTMLFormElement>('[data-account-form]'),status=document.querySelector<HTMLElement>('[data-account-status]'),list=document.querySelector<HTMLElement>('[data-account-list]');
 if(!form||!status||!list)return;
 const user=form.elements.namedItem('userId') as HTMLInputElement,artist=form.elements.namedItem('artistId') as HTMLSelectElement,venue=form.elements.namedItem('venueId') as HTMLSelectElement,administrator=form.elements.namedItem('administrator') as HTMLInputElement,save=form.querySelector<HTMLButtonElement>('button')!;
 async function api(path:string,body?:unknown){const response=await fetch('/api/community/'+path,{method:body?'PUT':'GET',headers:body?{'Content-Type':'application/json','x-aaj-prototype':'local'}:{},body:body?JSON.stringify(body):undefined});const result=await response.json();if(!response.ok)throw new Error(result.error||'Unable to load account access.');return result}
 async function refresh(){const {memberships}=await api('memberships');list!.replaceChildren();for(const member of memberships as Membership[]){const button=document.createElement('button');button.type='button';button.textContent=`${member.user_id}${member.user_id===form!.dataset.currentUser?' (you)':''} · ${member.artist_id||'No artist'} · ${member.venue_id||'No venue'}${member.administrator?' · Administrator':''}`;button.addEventListener('click',()=>{user.value=member.user_id;artist.value=member.artist_id||'';venue.value=member.venue_id||'';administrator.checked=member.administrator===1;status!.textContent='Review these permissions, then save to apply changes.';user.focus()});const row=document.createElement('p');row.append(button);list!.append(row)}}
 try{const {records}=await api('state');artist.add(new Option('Alan Just','artist-alan-just'));for(const record of records){if(record.collection==='applications'&&record.payload?.status==='approved'&&record.payload.invitationAccepted)artist.add(new Option(record.payload.name||record.id,record.id));if(record.collection==='venues'&&record.payload?.status==='approved')venue.add(new Option(record.payload.name||record.id,record.id))}await refresh();save.disabled=false}catch(error){status.textContent=error instanceof Error?error.message:'Unable to load account access.'}
 form.addEventListener('submit',async event=>{event.preventDefault();save.disabled=true;status.textContent='Checking the Clerk account and saving permissions…';try{await api('memberships',{userId:user.value.trim(),artistId:artist.value||null,venueId:venue.value||null,administrator:administrator.checked});await refresh();status.textContent='Account access saved. The person can reload their account page to see the assignment.'}catch(error){status.textContent=error instanceof Error?error.message:'Unable to save account access.'}finally{save.disabled=false}});
}
