import {getMemberArtist,saveMemberArtist,imageUrl,saveImage,memberUrl,type MemberArtist,type MemberWork} from './member-artists';
import pilot from '../data/community-pilot.json';
import {readShowings,renderShowings} from './prototype-showings';
const el=(tag:string,text='')=>{const node=document.createElement(tag);node.textContent=text;return node};
export async function initMemberSetup(){
 const id=new URLSearchParams(location.search).get('artist')||'',root=document.querySelector<HTMLElement>('[data-regular-workspace]');let serverInitial:MemberArtist|null=null;try{serverInitial=JSON.parse(root?.dataset.initialArtist||'null') as MemberArtist|null}catch{}const initial=getMemberArtist(id)||(serverInitial?.id===id?serverInitial:null);if(!initial){document.querySelector<HTMLElement>('[data-setup-unavailable]')!.hidden=false;return}let artist:MemberArtist=initial;
 document.querySelector<HTMLElement>('[data-setup-content]')!.hidden=false;document.querySelector('[data-setup-title]')!.textContent=document.querySelector('[data-regular-workspace="true"]')?`${artist.name}’s workspace`:`Welcome, ${artist.name}`;document.title=`${artist.name}’s workspace | Artists Are Jerks`;
 const message=document.querySelector('[data-setup-message]')!;
 const profile=document.querySelector<HTMLFormElement>('[data-setup-profile]')!,contact=document.querySelector<HTMLFormElement>('[data-setup-contact]')!,upload=document.querySelector<HTMLFormElement>('[data-member-upload]')!;
 const panels=[profile,contact,document.querySelector<HTMLElement>('[data-setup-artwork]')!,document.querySelector<HTMLElement>('[data-setup-preview]')!];
 const steps=[...document.querySelectorAll<HTMLButtonElement>('[data-setup-step]')];
 let selected:File|null=null,sample=false,previewUrl='',editingWorkId='';
 function persist(next:MemberArtist){try{saveMemberArtist(next);artist=next;message.textContent='Changes queued for shared storage; check the top banner for confirmation.';return true}catch{message.textContent='Unable to save. Browser storage may be full or blocked. Your current entries are still available here.';return false}}
 function summary(){const publicWorks=artist.works.filter(w=>w.public).length,root=document.querySelector('[data-setup-summary]')!;root.replaceChildren(el('p',`${artist.name} · ${artist.city} · ${artist.practice}`),el('p',`${artist.works.length} artworks · ${publicWorks} ${artist.published?'visible on your artist page':'ready for your artist page'}`),el('p',artist.published?'Your artist page is published and appears in Our Artists.':'Your artist page is offline. Publish it here to appear in Our Artists.'));document.querySelector<HTMLAnchorElement>('[data-member-preview]')!.href=memberUrl(id,true);document.querySelector<HTMLAnchorElement>('[data-member-create-showing]')!.href=`/prototype/onboarding/showing/?artist=${encodeURIComponent(id)}`;document.querySelector<HTMLButtonElement>('[data-offline-member]')!.hidden=!artist.published;document.querySelector<HTMLButtonElement>('[data-publish-member]')!.hidden=artist.published;const publicationStatus=document.querySelector<HTMLElement>('[data-artwork-publication-status]');if(publicationStatus)publicationStatus.textContent=artist.published?'Your artist page is published. Changes to included artwork will appear on it after you save.':`${publicWorks} ${publicWorks===1?'artwork is':'artworks are'} ready, but your artist page is offline. Open Visibility to preview and publish it.`;const artworkAction=document.querySelector<HTMLButtonElement>('[data-workspace-action="artwork"]');if(artworkAction)artworkAction.textContent=`Manage artwork (${artist.works.length})`;const visibilityAction=document.querySelector<HTMLButtonElement>('[data-workspace-action="visibility"]');if(visibilityAction)visibilityAction.textContent=artist.published?'Preview & visibility':'Publish artist page';}
 const regular=Boolean(document.querySelector('[data-regular-workspace="true"]'));let guided=!regular;
 const tabs=[...document.querySelectorAll<HTMLButtonElement>('[data-workspace-tab]')];
 function workspace(tab:string){
  if(tab==='showing'&&location.hash!=='#showing'){location.hash='showing';location.reload();return}
  guided=false;document.querySelector<HTMLElement>('[data-guided-nav]')!.hidden=true;
  panels.forEach((panel,index)=>panel.hidden=!(tab==='profile'&&index<2||tab==='artwork'&&index===2||tab==='visibility'&&index===3));
  document.querySelector<HTMLElement>('[data-workspace-home]')!.hidden=tab!=='home';document.querySelector<HTMLElement>('[data-workspace-showing]')!.hidden=tab!=='showing';
  tabs.forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.workspaceTab===tab)));
  history.replaceState(null,'',`#${tab}`);summary();
  document.querySelector('[data-workspace-overview]')!.textContent=`Your page is ${artist.published?'public':'offline'}. ${artist.works.length} artworks and ${readShowings().filter(s=>s.artistId===id).length} saved showings.`;
 }
 tabs.forEach(button=>button.addEventListener('click',()=>workspace(button.dataset.workspaceTab!)));
 document.querySelectorAll<HTMLButtonElement>('[data-workspace-action]').forEach(button=>button.addEventListener('click',()=>workspace(button.dataset.workspaceAction!)));
 document.querySelector('[data-resume-guide]')?.addEventListener('click',()=>{guided=true;document.querySelector<HTMLElement>('[data-workspace-home]')!.hidden=true;document.querySelector<HTMLElement>('[data-workspace-showing]')!.hidden=true;document.querySelector<HTMLElement>('[data-guided-nav]')!.hidden=false;tabs.forEach(b=>b.setAttribute('aria-pressed','false'));go(artist.works.length?3:0)});
 function go(step:number){if(regular&&!guided){workspace(step<2?'profile':step===2?'artwork':'visibility');return}if(step!==artist.step)persist({...artist,step});panels.forEach((panel,index)=>panel.hidden=index!==step);steps.forEach((button,index)=>button.setAttribute('aria-pressed',String(index===step)));summary()}
 for(const form of [profile,contact])for(const [name,value] of Object.entries(artist)){const field=form.elements.namedItem(name) as HTMLInputElement|null;if(!field)continue;if(field.type==='checkbox')field.checked=Boolean(value);else field.value=String(value)}
 steps.forEach((button,index)=>button.addEventListener('click',()=>go(index)));
 profile.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(profile);const name=String(data.get('name')).trim(),practice=String(data.get('practice')).trim();if(!name||!practice){message.textContent='Please enter your name and media.';return}if(persist({...artist,name,practice,city:String(data.get('city')),bio:String(data.get('bio')).trim()}))go(1)});
 contact.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(contact);const website=String(data.get('website')).trim(),email=String(data.get('email')).trim(),phone=String(data.get('phone')).trim();if(website&&!/^https?:\/\//i.test(website)){message.textContent='Use an http:// or https:// website address.';return}if((data.has('publicEmail')&&!email)||(data.has('publicPhone')&&!phone)||(data.has('publicWebsite')&&!website)){message.textContent='Enter a value for each contact method you want to show.';return}if(persist({...artist,website,email,phone,publicEmail:data.has('publicEmail'),publicWebsite:data.has('publicWebsite'),publicPhone:data.has('publicPhone')}))go(2)});
 const image=document.querySelector<HTMLImageElement>('[data-upload-preview]')!,uploadMessage=document.querySelector('[data-upload-message]')!;
 const input=upload.elements.namedItem('image') as HTMLInputElement;
 input.addEventListener('change',async()=>{selected=null;sample=false;if(previewUrl)URL.revokeObjectURL(previewUrl);image.hidden=true;const file=input.files?.[0];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024){uploadMessage.textContent='Choose a JPEG, PNG, or WebP up to 10 MB.';input.value='';return}try{const decoded=await createImageBitmap(file);decoded.close()}catch{uploadMessage.textContent='This file could not be read as an image.';input.value='';return}selected=file;previewUrl=URL.createObjectURL(file);image.src=previewUrl;image.hidden=false;uploadMessage.textContent='Image selected. Add details and save when ready.'});
 document.querySelector('[data-use-sample]')?.addEventListener('click',()=>{sample=true;selected=null;input.value='';image.src=pilot.artworks[0].image;image.hidden=false;(upload.elements.namedItem('title') as HTMLInputElement).value='Sample artwork — for layout only';uploadMessage.textContent='Sample image borrowed from Alan’s gallery for this prototype.'});
 const sale=upload.elements.namedItem('sale') as HTMLSelectElement,price=upload.elements.namedItem('price') as HTMLInputElement;
 sale.addEventListener('change',()=>{document.querySelector<HTMLElement>('[data-member-price]')!.hidden=sale.value!=='price';price.required=sale.value==='price'});
 const formTitle=document.querySelector<HTMLElement>('[data-artwork-form-title]')!,saveButton=document.querySelector<HTMLButtonElement>('[data-save-artwork]')!,cancelEdit=document.querySelector<HTMLButtonElement>('[data-cancel-artwork-edit]')!;
 function clearArtworkForm(){editingWorkId='';upload.reset();selected=null;sample=false;if(previewUrl){URL.revokeObjectURL(previewUrl);previewUrl=''}image.hidden=true;formTitle.textContent='Add artwork';saveButton.textContent='Save artwork';cancelEdit.hidden=true;document.querySelector<HTMLElement>('[data-member-price]')!.hidden=true;price.required=false}
 async function editWork(work:MemberWork){editingWorkId=work.id;selected=null;sample=false;if(previewUrl){URL.revokeObjectURL(previewUrl);previewUrl=''}(upload.elements.namedItem('title') as HTMLInputElement).value=work.title;(upload.elements.namedItem('medium') as HTMLInputElement).value=work.medium||'';(upload.elements.namedItem('year') as HTMLInputElement).value=work.year||'';sale.value=work.sale||'contact';price.value=work.price||'';(upload.elements.namedItem('public') as HTMLInputElement).checked=work.public;document.querySelector<HTMLElement>('[data-member-price]')!.hidden=sale.value!=='price';price.required=sale.value==='price';image.src=await imageUrl(work);image.hidden=false;formTitle.textContent=`Edit ${work.title}`;saveButton.textContent='Save changes';cancelEdit.hidden=false;uploadMessage.textContent='Change the details below. Choose a new image only if you want to replace the current one.';upload.scrollIntoView({behavior:'smooth',block:'start'})}
 cancelEdit.addEventListener('click',()=>{clearArtworkForm();uploadMessage.textContent='Editing canceled. Your saved artwork was not changed.'});
 async function works(){const root=document.querySelector('[data-member-works]')!;root.replaceChildren();for(const work of artist.works){const row=el('article');row.className='card';const img=document.createElement('img');img.src=await imageUrl(work);img.alt=work.title;img.style.cssText='width:100%;height:180px;object-fit:contain;background:#181818';const copy=document.createElement('div'),details=[work.medium,work.year].filter(Boolean).join(' · ');copy.append(el('h3',work.title));if(details)copy.append(el('p',details));copy.append(el('p',work.public?(artist.published?'Visible on your published artist page':'Included when your artist page is published'):'Private artwork'));const actions=document.createElement('div');actions.className='actions';const edit=document.createElement('button');edit.type='button';edit.textContent='Edit artwork';edit.addEventListener('click',()=>void editWork(work));const toggle=document.createElement('button');toggle.type='button';toggle.textContent=work.public?'Exclude from artist page':'Include on artist page';toggle.addEventListener('click',()=>{const updated=artist.works.map(w=>w.id===work.id?{...w,public:!w.public}:w);if(persist({...artist,works:updated,published:artist.published&&updated.some(w=>w.public)})){void works();summary()}});actions.append(edit,toggle);copy.append(actions);row.append(img,copy);root.append(row)}}
 upload.addEventListener('submit',async e=>{e.preventDefault();const existing=editingWorkId?artist.works.find(work=>work.id===editingWorkId):undefined;if(!existing&&!sample&&!selected){uploadMessage.textContent='Choose an artwork image, or use the labeled sample.';return}saveButton.disabled=true;const data=new FormData(upload),replacement=Boolean(sample||selected),imageKey=replacement?crypto.randomUUID():existing?.imageKey||crypto.randomUUID();const work:MemberWork={id:existing?.id||crypto.randomUUID(),title:String(data.get('title')||'').trim()||'Untitled',medium:String(data.get('medium')||'').trim(),year:String(data.get('year')||''),sale:String(data.get('sale')),price:sale.value==='price'?price.value:'',public:data.has('public'),imageKey,sampleImage:sample?pilot.artworks[0].image:replacement?'':existing?.sampleImage||''};try{if(selected)await saveImage(work.imageKey,selected);const updated=existing?artist.works.map(item=>item.id===existing.id?work:item):[...artist.works,work];if(persist({...artist,works:updated})){const wasEditing=Boolean(existing);clearArtworkForm();uploadMessage.textContent=wasEditing?'Artwork changes saved.':'Artwork saved. Add another piece or preview your page.';await works();summary()}}catch{uploadMessage.textContent='Image could not be saved. Allow browser storage and try again.'}finally{saveButton.disabled=false}});
 document.querySelector('[data-go-preview]')?.addEventListener('click',()=>go(3));document.querySelector('[data-publish-member]')?.addEventListener('click',()=>{if(!artist.name.trim()||!artist.practice.trim()){document.querySelector('[data-publication-message]')!.textContent='Save your name and media in Profile before publishing.';return}if(!artist.works.some(w=>w.public)){document.querySelector('[data-publication-message]')!.textContent='Add at least one artwork and include it on your artist page first.';return}if(persist({...artist,published:true})){summary();const root=document.querySelector('[data-publication-message]')!;root.replaceChildren(el('span','Your artist page is published and now appears in Our Artists. '));const link=document.createElement('a');link.href=memberUrl(id);link.textContent='View public page →';root.append(link)}});
 document.querySelector('[data-offline-member]')?.addEventListener('click',()=>{if(persist({...artist,published:false})){summary();document.querySelector('[data-publication-message]')!.textContent='Your page is offline. Your profile and artwork remain saved.'}});
 await works();if(regular){workspace(['home','profile','artwork','showing','visibility'].includes(location.hash.slice(1))?location.hash.slice(1):'home')}else go(Math.min(3,Math.max(0,artist.step)));window.addEventListener('pagehide',()=>{if(previewUrl)URL.revokeObjectURL(previewUrl)});
}
export async function initMemberPublicPage(){
 const id=new URLSearchParams(location.search).get('artist')||'',preview=new URLSearchParams(location.search).get('preview')==='1',artist=getMemberArtist(id);
 const status=document.querySelector('[data-member-page-status]')!;
 if(!artist||(!artist.published&&!preview)){document.querySelector('[data-member-name]')!.textContent='This artist page is not published';status.textContent='The artist can preview and publish this page from their workspace.';return}
 document.querySelector('[data-member-name]')!.textContent=artist.name;document.title=`${artist.name} | Artists Are Jerks`;if(preview)document.querySelector('[data-member-page-notice]')!.textContent='Private preview · Browser-only prototype';
 const showingRoot=document.querySelector<HTMLElement>('[data-browser-showings]');if(showingRoot){showingRoot.dataset.artist=id;await renderShowings(showingRoot)}
 document.querySelector('[data-member-city]')!.textContent=`${artist.city}, Oregon`;
 document.querySelector('[data-member-breadcrumb]')!.textContent=artist.name;
 document.querySelector('[data-member-address-name]')!.textContent=artist.name;
 const profile=document.querySelector('[data-member-public-profile]')!;const practice=el('p',artist.practice),bio=el('p',artist.bio),contacts=el('div');practice.className='practice';bio.className='bio';contacts.className='contact-actions';profile.append(practice,bio,contacts);
 const link=(text:string,url:string)=>{const a=document.createElement('a');a.textContent=text;a.href=url;contacts.append(a)};
 if(artist.publicWebsite&&/^https?:\/\//i.test(artist.website))link('Visit artist’s website',artist.website);if(artist.publicEmail)link('Email the artist',`mailto:${artist.email}`);if(artist.publicPhone){link('Call the artist',`tel:${artist.phone.replace(/[^+\d]/g,'')}`);link('Text the artist',`sms:${artist.phone.replace(/[^+\d]/g,'')}`)}
 const works=artist.works.filter(w=>w.public),root=document.querySelector('[data-member-public-works]')!,urls:string[]=[];const dialog=document.querySelector<HTMLDialogElement>('[data-member-viewer]')!,image=document.querySelector<HTMLImageElement>('[data-viewer-image]')!;let active=0;
 function display(index:number){active=(index+works.length)%works.length;image.src=urls[active];image.alt=works[active].title;document.querySelector('[data-viewer-caption]')!.textContent=`${works[active].title} · ${active+1} of ${works.length}`;}
 for(const work of works){let url='';try{url=await imageUrl(work)}catch{}urls.push(url);const index=urls.length-1;const card=el('article');card.className='artwork-card member-artwork';const button=document.createElement('button');button.type='button';button.className='artwork-image';button.setAttribute('aria-haspopup','dialog');button.setAttribute('aria-label',`Enlarge ${work.title}`);const img=document.createElement('img');img.alt=work.title;img.src=url;button.append(img);button.addEventListener('click',()=>{display(index);dialog.showModal()});const copy=el('div');copy.className='artwork-copy';const details=el('p',[work.medium,work.year].filter(Boolean).join(', '));details.className='details';copy.append(el('h3',work.title),details,el('p',work.sale==='price'?`$${Number(work.price).toLocaleString('en-US')}`:work.sale==='sold'?'Sold':work.sale==='not-for-sale'?'Not for sale':work.sale==='private'?'Price private':'Contact the artist for price'));copy.lastElementChild!.className='sale-state';card.append(button,copy);if(work.sampleImage)copy.append(el('p','Sample artwork — borrowed for prototype layout.'));root.append(card)}
 if(!works.length)status.textContent='No artwork selected for public display yet.';
 document.querySelector('[data-close-viewer]')?.addEventListener('click',()=>dialog.close());document.querySelector('[data-viewer-previous]')?.addEventListener('click',()=>display(active-1));document.querySelector('[data-viewer-next]')?.addEventListener('click',()=>display(active+1));dialog.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){e.preventDefault();display(active-1)}if(e.key==='ArrowRight'){e.preventDefault();display(active+1)}});window.addEventListener('pagehide',()=>urls.filter(u=>u.startsWith('blob:')).forEach(u=>URL.revokeObjectURL(u)));
}
