import {getStoredItem,setStoredItem,sharedStorageEnabled,sharedStorageRequired,publicStorageMode,api} from './community-storage';
import {readArtistApplications} from './artist-applications';
export const MEMBER_ARTISTS_KEY='aaj-member-artists-prototype';
export interface MemberWork {id:string;title:string;medium:string;year:string;sale:string;price:string;public:boolean;imageKey:string;sampleImage:string}
export interface MemberArtist {id:string;name:string;city:string;practice:string;bio:string;website:string;email:string;phone:string;publicWebsite:boolean;publicEmail:boolean;publicPhone:boolean;published:boolean;step:number;works:MemberWork[]}
export function readMemberArtists():MemberArtist[]{try{const data=JSON.parse(getStoredItem(MEMBER_ARTISTS_KEY)||'[]');return Array.isArray(data)?data:[]}catch{return []}}
export function saveMemberArtist(artist:MemberArtist){setStoredItem(MEMBER_ARTISTS_KEY,JSON.stringify([...readMemberArtists().filter(a=>a.id!==artist.id),artist]))}
export function getMemberArtist(id:string){const app=readArtistApplications().find(a=>a.id===id&&a.status==='approved'&&a.invitationAccepted);if(!app)return null;return readMemberArtists().find(a=>a.id===id)||{id,name:app.name,city:app.city,practice:app.practice,bio:'',website:app.portfolio,email:app.email,phone:'',publicWebsite:false,publicEmail:false,publicPhone:false,published:false,step:0,works:[]};}
export function memberUrl(id:string,preview=false){return `/prototype/artists/member/?artist=${encodeURIComponent(id)}${preview?'&preview=1':''}`}
async function imageDatabase(){return new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open('aaj-artwork-images-prototype',1);request.onupgradeneeded=()=>request.result.createObjectStore('images');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
export async function saveImage(key:string,blob:Blob){if(sharedStorageRequired()&&!sharedStorageEnabled())throw new Error('Shared storage is unavailable. Reload before uploading.');if(sharedStorageEnabled()){await api(`images/${encodeURIComponent(key)}`,{method:'PUT',body:blob});return}const db=await imageDatabase();try{await new Promise<void>((resolve,reject)=>{const transaction=db.transaction('images','readwrite');transaction.objectStore('images').put(blob,key);transaction.oncomplete=()=>resolve();transaction.onerror=()=>reject(transaction.error);transaction.onabort=()=>reject(transaction.error)})}finally{db.close()}}
export async function imageUrl(work:MemberWork){if(work.sampleImage)return work.sampleImage;if(sharedStorageEnabled())return `/api/community/${publicStorageMode()?'public/':''}images/${encodeURIComponent(work.imageKey)}`;const db=await imageDatabase();try{return await new Promise<string>((resolve,reject)=>{const request=db.transaction('images').objectStore('images').get(work.imageKey);request.onsuccess=()=>resolve(request.result?URL.createObjectURL(request.result):'');request.onerror=()=>reject(request.error)})}finally{db.close()}}
export async function renderMemberDirectory(){const root=document.querySelector('.member-grid');if(!root)return;root.querySelectorAll('[data-member-profile]').forEach(n=>n.remove());for(const artist of readMemberArtists().filter(a=>a.published&&getMemberArtist(a.id))){const work=artist.works.find(w=>w.public);if(!work)continue;const a=document.createElement('a');a.className='member-card';a.dataset.memberProfile=artist.id;a.href=memberUrl(artist.id);const image=document.createElement('img');image.alt=`Artwork by ${artist.name}`;image.src=await imageUrl(work);const copy=document.createElement('div');for(const [tag,text] of [['h3',artist.name],['p',artist.city],['p',artist.practice]]){const el=document.createElement(tag);el.textContent=text;copy.append(el)}a.append(image,copy);root.append(a)}}

export async function deleteMemberArtist(id:string){
 const artist=readMemberArtists().find(a=>a.id===id);
 setStoredItem(MEMBER_ARTISTS_KEY,JSON.stringify(readMemberArtists().filter(a=>a.id!==id)));
 if(!artist?.works.some(w=>w.imageKey&&!w.sampleImage))return;
 const db=await imageDatabase();try{await new Promise<void>((resolve,reject)=>{const transaction=db.transaction('images','readwrite');artist.works.filter(w=>!w.sampleImage).forEach(w=>transaction.objectStore('images').delete(w.imageKey));transaction.oncomplete=()=>resolve();transaction.onerror=()=>reject(transaction.error)})}finally{db.close()}
}
