export type ApplicationKind='artist'|'venue';
import {aiTag,artworkFrame} from './admin-moderation';
export interface SampleWork {id:string;title:string;imageKey:string;sampleImage:string;madeWithAI:boolean}
export interface SharedApplication {kind:ApplicationKind;id:string;userId:string;payload:Record<string,any>;revision:number;updatedAt:string;assignedArtistId:string|null;assignedVenueId:string|null;samples?:SampleWork[]}
export interface AdminNotification {id:string;kind:ApplicationKind|'region';subject_id:string;title:string;delivery_status:'pending'|'sent'|'not_configured'|'failed';error:string|null;created_at:string;delivered_at:string|null}
export interface RegionProposal {id:string;user_id:string;proposed_name:string;core_city:string;state_code:string;coverage:string;local_connection:string;intended_role:string;rationale:string;status:'pending'|'approved'|'declined';region_id:string|null;created_at:string}
const element=(tag:string,text='',className='')=>{const node=document.createElement(tag);node.textContent=text;node.className=className;return node};
const button=(text:string,handler:()=>void)=>{const node=element('button',text) as HTMLButtonElement;node.type='button';node.addEventListener('click',handler);return node};
export async function applicationApi(body?:unknown){const response=await fetch('/api/community/applications',{method:body?'PUT':'GET',headers:{Accept:'application/json',...(body?{'Content-Type':'application/json','x-aaj-prototype':'local'}:{})},body:body?JSON.stringify(body):undefined});const result=await response.json().catch(()=>({error:'The server returned an unreadable response.'}));if(!response.ok)throw new Error(result.error||'Unable to process the application.');return result as {saved?:boolean;id?:string;applications:SharedApplication[];notifications:AdminNotification[];emailConfigured:boolean}}
async function regionApi(body?:unknown){const response=await fetch('/api/community/region-proposals',{method:body?'PUT':'GET',headers:{Accept:'application/json',...(body?{'Content-Type':'application/json','x-aaj-prototype':'local'}:{})},body:body?JSON.stringify(body):undefined});const result=await response.json().catch(()=>({error:'The server returned an unreadable response.'}));if(!response.ok)throw new Error(result.error||'Unable to process the region proposal.');return result as {proposals:RegionProposal[]}}

export function initVenueApplication(){
 const form=document.querySelector<HTMLFormElement>('[data-venue-application]');if(!form)return;const status=document.querySelector<HTMLElement>('[data-venue-application-status]')!,list=document.querySelector<HTMLElement>('[data-my-venue-applications]')!;
 async function render(){try{const {applications}=await applicationApi();const venues=applications.filter(entry=>entry.kind==='venue');list.replaceChildren();if(!venues.length)list.append(element('p','You have not submitted a venue application.'));venues.forEach(({payload})=>{const card=element('article','', 'card');card.append(element('h2',payload.name),element('p',`${payload.status} · ${payload.city} · ${payload.type}`));if(payload.status==='approved')card.append(element('p','Approved. An administrator can now assign this venue workspace to your account.'));list.append(card)})}catch(error){list.replaceChildren(element('p',error instanceof Error?error.message:'Unable to load applications.'))}}
 form.addEventListener('submit',async event=>{event.preventDefault();status.textContent='Submitting…';const data=new FormData(form),value=(name:string)=>String(data.get(name)||'').trim();const payload={name:value('name'),type:value('type'),regionId:value('regionId'),city:value('city'),address:value('address'),postalCode:value('postalCode'),description:value('description'),website:value('website'),phone:value('phone'),hours:value('hours'),accessibility:value('accessibility'),instructions:value('instructions'),contactName:value('contactName'),email:value('email'),opportunities:value('opportunities'),available:data.has('available')};try{await applicationApi({kind:'venue',payload});form.reset();status.textContent='Your venue application is awaiting administrator review.';await render()}catch(error){status.textContent=error instanceof Error?error.message:'Unable to submit this application.'}});void render();
}

export function initAdminInbox(){
 const found=document.querySelector<HTMLElement>('[data-admin-inbox]');if(!found)return;const root=found,counts=document.querySelector<HTMLElement>('[data-inbox-counts]')!,status=document.querySelector<HTMLElement>('[data-inbox-status]')!,alerts=document.querySelector<HTMLElement>('[data-notification-status]')!;
 async function reviewApplication(entry:SharedApplication,decision:'approved'|'declined'){status.textContent=`Saving ${entry.payload.name}…`;try{await applicationApi({action:'review',kind:entry.kind,id:entry.id,status:decision});status.textContent=`${entry.payload.name} is ${decision}.`;await render()}catch(error){status.textContent=error instanceof Error?error.message:'Unable to review this application.'}}
 async function resendApproval(entry:SharedApplication){status.textContent=`Emailing ${entry.payload.name}…`;try{const result=await applicationApi({action:'resend-approval',id:entry.id}) as {approvalEmail?:string};status.textContent=result.approvalEmail==='sent'?`Approval email sent to ${entry.payload.name}.`:'The approval email didn’t go through. Check the email setup.';await render()}catch(error){status.textContent=error instanceof Error?error.message:'Unable to send the approval email.'}}
 async function reviewRegion(proposal:RegionProposal,decision:'approved'|'declined'){status.textContent=`Saving ${proposal.proposed_name}…`;try{await regionApi({action:'review',id:proposal.id,status:decision});status.textContent=`${proposal.proposed_name} is ${decision}.`;await render()}catch(error){status.textContent=error instanceof Error?error.message:'Unable to review this proposal.'}}
 async function render(){try{const [{applications,notifications,emailConfigured},{proposals}]=await Promise.all([applicationApi(),regionApi()]);const pendingApplications=applications.filter(entry=>entry.payload.status==='pending'),pendingRegions=proposals.filter(proposal=>proposal.status==='pending');counts.textContent=`${pendingApplications.filter(entry=>entry.kind==='artist').length} artists · ${pendingApplications.filter(entry=>entry.kind==='venue').length} venues · ${pendingRegions.length} regions awaiting review`;const unsent=notifications.filter(item=>item.delivery_status!=='sent');alerts.textContent=!emailConfigured?'Email alert delivery is not active yet. Every application still appears in this inbox.':unsent.length?`${unsent.length} email alert${unsent.length===1?' needs':'s need'} attention. Application records remain available below.`:'Email alerts are active.';root.replaceChildren();
  const combined=[...applications.map(entry=>({created:entry.updatedAt,type:entry.kind,entry})),...proposals.map(proposal=>({created:proposal.created_at,type:'region' as const,proposal}))].sort((a,b)=>b.created.localeCompare(a.created));if(!combined.length)root.append(element('p','No applications have been submitted.'));
  combined.forEach(item=>{if(item.type==='region'){const proposal=item.proposal!;const card=element('article','', 'card');card.append(element('p','REGION PROPOSAL'),element('h2',proposal.proposed_name),element('p',`${proposal.status} · ${proposal.core_city}, ${proposal.state_code}`),element('p',proposal.coverage),element('p',`Applicant account: ${proposal.user_id}`),element('h3','Connection to the area'),element('p',proposal.local_connection),element('h3','Intended role'),element('p',proposal.intended_role),element('h3','Why this area'),element('p',proposal.rationale));if(proposal.status==='pending'){const actions=element('div','', 'actions');actions.append(button('Approve region',()=>void reviewRegion(proposal,'approved')),button('Decline',()=>void reviewRegion(proposal,'declined')));card.append(actions)}root.append(card);return}
   const entry=item.entry!,payload=entry.payload,card=element('article','', 'card');card.append(element('p',entry.kind==='artist'?'ARTIST APPLICATION':'VENUE APPLICATION'),element('h2',payload.name),element('p',`${payload.status} · ${payload.city}`),element('p',`Applicant account: ${entry.userId}`),element('p',`Private contact: ${payload.contactName?payload.contactName+' · ':''}${payload.email}`));if(entry.kind==='artist'){card.append(element('p',payload.practice),element('p',payload.note),element('p',payload.terms?`Agreed to the Artist Terms (version ${payload.terms.version}) on ${new Date(payload.terms.agreedAt).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}.`:'Hasn’t agreed to the Artist Terms yet.'));
    // The pieces they sent, big enough to judge.
    const samples=entry.samples??[];
    if(samples.length){const strip=element('div','','sample-strip');strip.append(...samples.map(work=>{const figure=element('figure'),caption=element('figcaption',work.title||'Untitled');if(work.madeWithAI)caption.append(document.createTextNode(' '),aiTag());figure.append(artworkFrame(work.imageKey,work.sampleImage,work.title),caption);return figure}));card.append(strip)}
    else if(payload.status==='pending')card.append(element('p','No pieces yet. They’ve been asked for two or three before this goes further.'));
    if(payload.status==='pending'&&!(Array.isArray(payload.samples)&&payload.samples.length)&&samples.length)card.append(element('p','These are the first pieces on their page. The request itself came in before sample pieces were required.'))}else card.append(element('p',`${payload.type} · ${payload.address}`),element('p',payload.description||''),element('p',payload.opportunities||''));if(payload.status==='pending'){const actions=element('div','', 'actions');actions.append(button(`Approve ${entry.kind}`,()=>void reviewApplication(entry,'approved')),button('Decline',()=>void reviewApplication(entry,'declined')));card.append(actions)}if(payload.status==='approved'||entry.kind==='artist'){
    const assignedId=entry.kind==='artist'?entry.assignedArtistId:entry.assignedVenueId;
    if(entry.kind==='artist'&&payload.status==='declined')card.append(element('p','Declined. Their private workspace is closed.'));
    else if(entry.kind==='artist'&&payload.status==='pending')card.append(element('p',assignedId===entry.id?'Their private page is already open, so they can build it while you review. Approving lets them publish it.':'Approving opens their page.'));
    else if(entry.kind==='artist'&&assignedId===entry.id){
     const sent=payload.approvalEmail;
     card.append(element('p','Approved. They can publish their page whenever they’re ready.'),element('p',sent==='sent'?`Approval email sent to ${payload.email}.`:sent==='failed'?'The approval email didn’t go through.':sent==='not_configured'?'Approval email isn’t set up on this site.':'No approval email has been sent.'));
     const actions=element('div','','actions');actions.append(button(sent==='sent'?'Send the approval email again':'Send the approval email',()=>void resendApproval(entry)));card.append(actions);
    }
    else if(assignedId===entry.id)card.append(element('p','Workspace assigned to this account.'));
    else if(assignedId)card.append(element('p',`This account already owns the ${assignedId} workspace. Use a separate applicant account for this test; assigning this application would replace the current workspace.`));
    else {const link=element('a','Assign workspace →') as HTMLAnchorElement;link.href=`/prototype/admin/accounts/?user=${encodeURIComponent(entry.userId)}`;card.append(link)}
   }root.append(card)});
 }catch(error){root.replaceChildren(element('p',error instanceof Error?error.message:'Unable to load the administrator inbox.'))}}
 void render();
}
