export type ApplicationKind='artist'|'venue';
export interface SharedApplication {kind:ApplicationKind;id:string;userId:string;payload:Record<string,any>;revision:number;updatedAt:string}
export interface AdminNotification {id:string;kind:ApplicationKind|'region';subject_id:string;title:string;delivery_status:'pending'|'sent'|'not_configured'|'failed';error:string|null;created_at:string;delivered_at:string|null}
export interface RegionProposal {id:string;user_id:string;proposed_name:string;core_city:string;state_code:string;coverage:string;local_connection:string;intended_role:string;rationale:string;status:'pending'|'approved'|'declined';region_id:string|null;created_at:string}
const element=(tag:string,text='',className='')=>{const node=document.createElement(tag);node.textContent=text;node.className=className;return node};
const button=(text:string,handler:()=>void)=>{const node=element('button',text) as HTMLButtonElement;node.type='button';node.addEventListener('click',handler);return node};
export async function applicationApi(body?:unknown){const response=await fetch('/api/community/applications',{method:body?'PUT':'GET',headers:{Accept:'application/json',...(body?{'Content-Type':'application/json','x-aaj-prototype':'local'}:{})},body:body?JSON.stringify(body):undefined});const result=await response.json().catch(()=>({error:'The server returned an unreadable response.'}));if(!response.ok)throw new Error(result.error||'Unable to process the application.');return result as {saved?:boolean;id?:string;applications:SharedApplication[];notifications:AdminNotification[];emailConfigured:boolean}}
async function regionApi(body?:unknown){const response=await fetch('/api/community/region-proposals',{method:body?'PUT':'GET',headers:{Accept:'application/json',...(body?{'Content-Type':'application/json','x-aaj-prototype':'local'}:{})},body:body?JSON.stringify(body):undefined});const result=await response.json().catch(()=>({error:'The server returned an unreadable response.'}));if(!response.ok)throw new Error(result.error||'Unable to process the region proposal.');return result as {proposals:RegionProposal[]}}

export function initVenueApplication(){
 const form=document.querySelector<HTMLFormElement>('[data-venue-application]');if(!form)return;const status=document.querySelector<HTMLElement>('[data-venue-application-status]')!,list=document.querySelector<HTMLElement>('[data-my-venue-applications]')!;
 async function render(){try{const {applications}=await applicationApi();const venues=applications.filter(entry=>entry.kind==='venue');list.replaceChildren();if(!venues.length)list.append(element('p','You have not submitted a venue application.'));venues.forEach(({payload})=>{const card=element('article','', 'card');card.append(element('h2',payload.name),element('p',`${payload.status} · ${payload.city} · ${payload.type}`));if(payload.status==='approved')card.append(element('p','Approved. An administrator can now assign this venue workspace to your account.'));list.append(card)})}catch(error){list.replaceChildren(element('p',error instanceof Error?error.message:'Unable to load applications.'))}}
 form.addEventListener('submit',async event=>{event.preventDefault();status.textContent='Submitting…';const data=new FormData(form),value=(name:string)=>String(data.get(name)||'').trim();const payload={name:value('name'),type:value('type'),regionId:value('regionId'),city:value('city'),address:value('address'),postalCode:value('postalCode'),description:value('description'),website:value('website'),phone:value('phone'),hours:value('hours'),accessibility:value('accessibility'),instructions:value('instructions'),contactName:value('contactName'),email:value('email'),opportunities:value('opportunities'),available:data.has('available')};try{await applicationApi({kind:'venue',payload});form.reset();status.textContent='Your venue application is awaiting administrator review.';await render()}catch(error){status.textContent=error instanceof Error?error.message:'Unable to submit this application.'}});void render();
}

export function initAdminInbox(){
 const found=document.querySelector<HTMLElement>('[data-admin-inbox]');if(!found)return;const root=found,counts=document.querySelector<HTMLElement>('[data-inbox-counts]')!,status=document.querySelector<HTMLElement>('[data-inbox-status]')!,alerts=document.querySelector<HTMLElement>('[data-notification-status]')!;
 async function reviewApplication(entry:SharedApplication,decision:'approved'|'declined'){status.textContent=`Saving ${entry.payload.name}…`;try{await applicationApi({action:'review',kind:entry.kind,id:entry.id,status:decision});status.textContent=`${entry.payload.name} is ${decision}.`;await render()}catch(error){status.textContent=error instanceof Error?error.message:'Unable to review this application.'}}
 async function reviewRegion(proposal:RegionProposal,decision:'approved'|'declined'){status.textContent=`Saving ${proposal.proposed_name}…`;try{await regionApi({action:'review',id:proposal.id,status:decision});status.textContent=`${proposal.proposed_name} is ${decision}.`;await render()}catch(error){status.textContent=error instanceof Error?error.message:'Unable to review this proposal.'}}
 async function render(){try{const [{applications,notifications,emailConfigured},{proposals}]=await Promise.all([applicationApi(),regionApi()]);const pendingApplications=applications.filter(entry=>entry.payload.status==='pending'),pendingRegions=proposals.filter(proposal=>proposal.status==='pending');counts.textContent=`${pendingApplications.filter(entry=>entry.kind==='artist').length} artists · ${pendingApplications.filter(entry=>entry.kind==='venue').length} venues · ${pendingRegions.length} regions awaiting review`;const unsent=notifications.filter(item=>item.delivery_status!=='sent');alerts.textContent=!emailConfigured?'Email alert delivery is not active yet. Every application still appears in this inbox.':unsent.length?`${unsent.length} email alert${unsent.length===1?' needs':'s need'} attention. Application records remain available below.`:'Email alerts are active.';root.replaceChildren();
  const combined=[...applications.map(entry=>({created:entry.updatedAt,type:entry.kind,entry})),...proposals.map(proposal=>({created:proposal.created_at,type:'region' as const,proposal}))].sort((a,b)=>b.created.localeCompare(a.created));if(!combined.length)root.append(element('p','No applications have been submitted.'));
  combined.forEach(item=>{if(item.type==='region'){const proposal=item.proposal!;const card=element('article','', 'card');card.append(element('p','REGION PROPOSAL'),element('h2',proposal.proposed_name),element('p',`${proposal.status} · ${proposal.core_city}, ${proposal.state_code}`),element('p',proposal.coverage),element('p',`Applicant account: ${proposal.user_id}`),element('h3','Connection to the area'),element('p',proposal.local_connection),element('h3','Intended role'),element('p',proposal.intended_role),element('h3','Why this area'),element('p',proposal.rationale));if(proposal.status==='pending'){const actions=element('div','', 'actions');actions.append(button('Approve region',()=>void reviewRegion(proposal,'approved')),button('Decline',()=>void reviewRegion(proposal,'declined')));card.append(actions)}root.append(card);return}
   const entry=item.entry!,payload=entry.payload,card=element('article','', 'card');card.append(element('p',entry.kind==='artist'?'ARTIST APPLICATION':'VENUE APPLICATION'),element('h2',payload.name),element('p',`${payload.status} · ${payload.city}`),element('p',`Applicant account: ${entry.userId}`),element('p',`Private contact: ${payload.contactName?payload.contactName+' · ':''}${payload.email}`));if(entry.kind==='artist')card.append(element('p',payload.practice),element('p',payload.note));else card.append(element('p',`${payload.type} · ${payload.address}`),element('p',payload.description||''),element('p',payload.opportunities||''));if(payload.status==='pending'){const actions=element('div','', 'actions');actions.append(button(`Approve ${entry.kind}`,()=>void reviewApplication(entry,'approved')),button('Decline',()=>void reviewApplication(entry,'declined')));card.append(actions)}if(payload.status==='approved'){const link=element('a','Assign workspace →') as HTMLAnchorElement;link.href=`/prototype/admin/accounts/?user=${encodeURIComponent(entry.userId)}`;card.append(link)}root.append(card)});
 }catch(error){root.replaceChildren(element('p',error instanceof Error?error.message:'Unable to load the administrator inbox.'))}}
 void render();
}
